# Fix panic from segfaults caused by continuing from a failed condition

**yorinasub17** commented *Nov 30, 2018*

This replaces the `if err != nil { assert.Fail() }` calls with `require.NoError`. Aside from being slightly more readable, the switch to using `require` as opposed to `assert` allows the test to exit when it shouldn't continue. By doing so, we can avoid panics halting the test and leaving resources lying around like in [this failure](https://circleci.com/gh/gruntwork-io/cloud-nuke/5857).
<br />
***


**yorinasub17** commented *Nov 30, 2018*

Yup! Jim pointed it out to me on one of the PRs and have since been using it religiously :)
***

**yorinasub17** commented *Nov 30, 2018*

Merging!
***

